openapi: 3.0.0

servers:
  - url: 'http://localhost:8080'

info:
  description: This is API specification for the REST API
  version: "1.0.0"
  title: smela
  contact:
    email: slava.melanko@gmail.com

tags:
  - name: common

paths:
  /heartbeat:
    get:
      tags:
        - common
      summary: |
        Verifies service health
      responses:
        '200':
          description: Returns API version, e.g. '1.0.0'

