
version: '3'

networks:
  monitor-net:

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.3.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: on-failure

  node-exporter:
    image: prom/node-exporter:v0.16.0
    depends_on:
      - prometheus
    ports:
      - 9100:9100
    networks:
      - monitor-net
    restart: on-failure

  grafana:
    image: grafana/grafana:5.1.4
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=qweqwe
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitor-net
    restart: on-failure
